import { describe, expect, it } from "vitest";
import { getAndValidateFile } from "../lexer/getAndValidateFile";
import { MOCK_PATH } from "./consts";
import { generateStringsOfFile, writeFile } from "./parser";

describe("parser tests", () => {
  it("file is of type object", () => {
    expect(typeof getAndValidateFile(MOCK_PATH)).toBe("object");
  });

  it("generates strings", async () => {
    const strings = await generateStringsOfFile();
    console.log("strings", strings);
    // expect(strings).toMatchInlineSnapshot(`
    //   [
    //     "//AUTOGENERATED FILE - DO NOT EDIT MANUALLY",
    //     "
    //   ",
    //     "
    //   ",
    //     "/** GET /artists */
    //   type GetArtistsDTO = {
    //       artist_name: string;
    //       artist_genre: string;
    //       albums_recorded: number;
    //       username: string;
    //   };",
    //     "
    //   ",
    //     "
    //   ",
    //     "export {GetArtistsDTO}",
    //   ]
    // `);
  });

  it("creates a file", () => {
    writeFile();
  });
});
