import fs from "fs";
import openapiTS from "openapi-typescript";

const writeYamlFileToTs = async () => {
  const localPath = new URL("../mocks/artists.yml", import.meta.url); // may be YAML or JSON format
  return await openapiTS(localPath);
};

const writeTsSchemaToFile = async (schema: string) => {
  //write schema to file
  const localPath = new URL(
    "../mocks/artistsAutoGenerated.ts",
    import.meta.url
  );
  fs.writeFileSync(localPath, schema);
};

export { writeYamlFileToTs, writeTsSchemaToFile };
