export const MOCK_PATH = "src/mocks/artists.yml";
export const MOCK_PATH_RELATIVE = "../mocks/artists.yml";
export const EXPORT_PATH = "../mocks/artistsAutoGenerated.ts";
export const EXPORT_PATH_ABSOLUTE = "src/mocks/artistsAutoGenerated.ts";
