/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/artists": {
    /** @description Returns a list of artists */
    get: {
      /** @description Returns a list of artists */
      responses: {
        /** @description Successfully returned a list of artists */
        200: {
          content: {
            "application/json": ({
                artist_name?: string;
                artist_genre?: string;
                albums_recorded?: number;
                username: string;
              })[];
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": {
              message?: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
