// Generated by ts-to-zod
import { z } from "zod";

export const pathsSchema = z.object({
    "/artists": z.object({
        get: z.object({
            responses: z.object({})
        })
    })
});

export const webhooksSchema = z.record(z.never());

export const componentsSchema = z.object({
    schemas: z.never(),
    responses: z.never(),
    parameters: z.never(),
    requestBodies: z.never(),
    headers: z.never(),
    pathItems: z.never()
});

export const externalSchema = z.record(z.never());

export const operationsSchema = z.record(z.never());
